### ISSUE TITLE
Make more customisable properties public

### ISSUE THREAD

**Issue by Emailrus** [bfeher/BFPaperCheckbox#8]
So it would be similar to BFPaperTableViewCell for example.
Things like animation duration, bubble sizes, burst size, etc.

**Comment by bfeher** [comment]
Hi @Emailrus !

Thanks for using this control :)

Your wish is my command! I've updated the control to give access to many more properties. The new cocoapod is version 2.0.0.  
Be careful though, because I made a lot of changes to property names in the process, hence the 1.x to 2.x update!
Also included in this update is full storyboard support. You can now place and design BFPaperCheckboxes directly in the storyboard. Just drag and drop a UIView and change its class to BFPaperCheckbox and all the properties become visible right there!

Enjoy. If you have any more wishes or find some bugs, please let me know!

**Comment by Emailrus** [comment]
Wow, you are fast and awesome
